server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://dev.triphos.co.kr:23306/dev_standard?allowMultiQueries=true
    username: dev_standard
    password: $tri0605!
springdoc:
  api-docs:
    path: /api-docs  # API 문서 경로 변경 (기본: /v3/api-docs)
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 경로 (기본: /swagger-ui/index.html)
    operations-sorter: alpha  # API 정렬
file:
  upload-dir: C:/triphos/files/