spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: xxxxxxxxxxx
            clientSecret: xxxxxxxxxxx

jwt:
  secret: D028EDB3E02CB03CB6BB1680A6B33145D1116D91555BCC4D815D560C93EE4492
