server:
  port: 8080

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/development_standard?allowMultiQueries=true
    username: root
    password: blackmusicnote14
  devtools:
    restart:
      enabled: false
  jpa:
    show-sql: true # jpa 쿼리출력여부
    properties:
      hibernate:
        format_sql: true # SQL 포맷팅
        highlight_sql: true # ANSI 코드에 색을 나타낸다
        use_sql_comments: true # SQL 내부에 /* */ 주석 추가
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type: trace

