server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    connection-timeout: 10s #커넥션 타임아웃 시간
spring:
  profiles:
    include: secret
    active: prod
  datasource:
    hikari:
      connection-timeout: 10000 #db 10초이상 응답없으면 타임아웃
      validation-timeout: 10000 #커넥션 유효성 검사 타임아웃
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  devtools:
    restart:
      enabled: false
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true
      highlight_sql: true # ANSI 코드에 색을 나타낸다
      dialect: org.hibernate.dialect.H2Dialect
      show-sql: true
      properties:
         hibernate:
           format_sql: true
  logging:
    level:
      org.hibernate.SQL: debug  # 실제 실행되는 SQL
      org.hibernate.type: trace  # 바인딩되는 파라미터 값까지 출력

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false


