server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    connection-timeout: 10s #커넥션 타임아웃 시간
spring:
  profiles:
    include: secret
    active: local
  datasource:
    hikari:
      connection-timeout: 10000 #db 10초이상 응답없으면 타임아웃
      validation-timeout: 10000 #커넥션 유효성 검사 타임아웃
  devtools:
    restart:
      enabled: false
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true # ANSI 코드에 색을 나타낸다
        dialect: org.hibernate.dialect.H2Dialect
  graphql:
    cors:
      allowed-origins: "*"
logging:
  level:
    org.mybatis: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.web.socket: WARN
    org.hibernate:
      SQL: WARN  # 실제 실행되는 SQL
      type: WARN  # 바인딩되는 파라미터 값까지 출력
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL
    call-setters-on-nulls: true
  type-aliases-package: kr.co.triphos
  mapper-locations: classpath:mapper/**/*.xml
springdoc:
  cache:
    disabled: true
  swagger-ui:
    path: /api-docs
    tags-sorter: alpha
    operations-sorter: method
  paths-to-exclude:
    - /common/**
    - /command/**
  doc-locations: classpath:/swagger/ # custom option
  api-docs:
    groups:
      enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
chat:
  unread-chat-room: "/user/queue/unread"
  send-msg: "/topic/chat/"
  watching: ":chatRoom" #memberId:chatRoom 형태